2020/10/28 09:20:20 [error] 22#22: *2 FastCGI sent in stderr: "PHP message: [info] Matched route "".
PHP message: [debug] Notified event "kernel.request" to listener "Symfony\Component\HttpKernel\EventListener\DebugHandlersListener::configure".
PHP message: [debug] Notified event "kernel.request" to listener "Symfony\Component\HttpKernel\EventListener\ValidateRequestListener::onKernelRequest".
PHP message: [debug] Notified event "kernel.request" to listener "Symfony\Component\HttpKernel\EventListener\SessionListener::onKernelRequest".
PHP message: [debug] Notified event "kernel.request" to listener "Symfony\Component\HttpKernel\EventListener\LocaleListener::setDefaultLocale".
PHP message: [debug] Notified event "kernel.request" to listener "Symfony\Component\HttpKernel\EventListener\RouterListener::onKernelRequest".
PHP message: [debug] Notified event "kernel.request" to listener "Symfony\Component\HttpKernel\EventListener\LocaleListener::onKernelRequest".
PHP message: [debug] Notified event "kernel.controller" to listener "Sensio\Bundle\FrameworkExtraBundle\EventListener\ControllerListener::onKernelController".
PHP message: [debug] Notified event "kernel.controller" to listener "Sensio\Bundle\FrameworkExtraBundle\EventListener\ParamConverterListener::onKernelController".
PHP message: [debug] Notified event "kernel.controller" to listener "Sensio\Bundle\FrameworkExtraBundle\EventListener\HttpCacheListener::onKernelController".
PHP message: [debug] Notified event "kernel.controller" to listener "Sensio\Bundle\FrameworkExtraBundle\EventListener\TemplateListener::onKernelController".
PHP message: [debug] Notified event "kernel.controller_arguments" to listener "Symfony\Component\HttpKernel\EventListener\ErrorListener::onControllerArguments".
PHP message: [debug] Notified event "kernel.controller_arguments" to listener "Sensio\Bundle\FrameworkExtraBundle\EventListener\IsGrantedListener::onKernelControllerArguments".
PHP message: [debug] Notified event "kernel.response" to listener "Symfony\Component\HttpKernel\Event
2020/10/28 09:20:23 [error] 22#22: *2 FastCGI sent in stderr: "PHP message: [info] Matched route "".
PHP message: [debug] Notified event "kernel.request" to listener "Symfony\Component\HttpKernel\EventListener\DebugHandlersListener::configure".
PHP message: [debug] Notified event "kernel.request" to listener "Symfony\Component\HttpKernel\EventListener\ValidateRequestListener::onKernelRequest".
PHP message: [debug] Notified event "kernel.request" to listener "Symfony\Component\HttpKernel\EventListener\SessionListener::onKernelRequest".
PHP message: [debug] Notified event "kernel.request" to listener "Symfony\Component\HttpKernel\EventListener\LocaleListener::setDefaultLocale".
PHP message: [debug] Notified event "kernel.request" to listener "Symfony\Component\HttpKernel\EventListener\RouterListener::onKernelRequest".
PHP message: [debug] Notified event "kernel.request" to listener "Symfony\Component\HttpKernel\EventListener\LocaleListener::onKernelRequest".
PHP message: [debug] Notified event "kernel.controller" to listener "Sensio\Bundle\FrameworkExtraBundle\EventListener\ControllerListener::onKernelController".
PHP message: [debug] Notified event "kernel.controller" to listener "Sensio\Bundle\FrameworkExtraBundle\EventListener\ParamConverterListener::onKernelController".
PHP message: [debug] Notified event "kernel.controller" to listener "Sensio\Bundle\FrameworkExtraBundle\EventListener\HttpCacheListener::onKernelController".
PHP message: [debug] Notified event "kernel.controller" to listener "Sensio\Bundle\FrameworkExtraBundle\EventListener\TemplateListener::onKernelController".
PHP message: [debug] Notified event "kernel.controller_arguments" to listener "Symfony\Component\HttpKernel\EventListener\ErrorListener::onControllerArguments".
PHP message: [debug] Notified event "kernel.controller_arguments" to listener "Sensio\Bundle\FrameworkExtraBundle\EventListener\IsGrantedListener::onKernelControllerArguments".
PHP message: [debug] Notified event "kernel.response" to listener "Symfony\Component\HttpKernel\Event
2020/10/28 09:20:24 [error] 22#22: *2 FastCGI sent in stderr: "PHP message: [info] Matched route "".
PHP message: [debug] Notified event "kernel.request" to listener "Symfony\Component\HttpKernel\EventListener\DebugHandlersListener::configure".
PHP message: [debug] Notified event "kernel.request" to listener "Symfony\Component\HttpKernel\EventListener\ValidateRequestListener::onKernelRequest".
PHP message: [debug] Notified event "kernel.request" to listener "Symfony\Component\HttpKernel\EventListener\SessionListener::onKernelRequest".
PHP message: [debug] Notified event "kernel.request" to listener "Symfony\Component\HttpKernel\EventListener\LocaleListener::setDefaultLocale".
PHP message: [debug] Notified event "kernel.request" to listener "Symfony\Component\HttpKernel\EventListener\RouterListener::onKernelRequest".
PHP message: [debug] Notified event "kernel.request" to listener "Symfony\Component\HttpKernel\EventListener\LocaleListener::onKernelRequest".
PHP message: [debug] Notified event "kernel.controller" to listener "Sensio\Bundle\FrameworkExtraBundle\EventListener\ControllerListener::onKernelController".
PHP message: [debug] Notified event "kernel.controller" to listener "Sensio\Bundle\FrameworkExtraBundle\EventListener\ParamConverterListener::onKernelController".
PHP message: [debug] Notified event "kernel.controller" to listener "Sensio\Bundle\FrameworkExtraBundle\EventListener\HttpCacheListener::onKernelController".
PHP message: [debug] Notified event "kernel.controller" to listener "Sensio\Bundle\FrameworkExtraBundle\EventListener\TemplateListener::onKernelController".
PHP message: [debug] Notified event "kernel.controller_arguments" to listener "Symfony\Component\HttpKernel\EventListener\ErrorListener::onControllerArguments".
PHP message: [debug] Notified event "kernel.controller_arguments" to listener "Sensio\Bundle\FrameworkExtraBundle\EventListener\IsGrantedListener::onKernelControllerArguments".
PHP message: [debug] Notified event "kernel.response" to listener "Symfony\Component\HttpKernel\Event
2020/11/05 12:05:51 [error] 32#32: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.16.1, server: , request: "GET / HTTP/1.1", upstream: "fastcgi://192.168.16.3:9000", host: "localhost"
2020/11/05 12:05:51 [error] 32#32: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.16.1, server: , request: "GET /favicon.ico HTTP/1.1", upstream: "fastcgi://192.168.16.3:9000", host: "localhost", referrer: "http://localhost/"
2020/11/05 12:05:52 [error] 32#32: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.16.1, server: , request: "GET / HTTP/1.1", upstream: "fastcgi://192.168.16.3:9000", host: "localhost"
2020/11/05 12:05:53 [error] 32#32: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.16.1, server: , request: "GET /favicon.ico HTTP/1.1", upstream: "fastcgi://192.168.16.3:9000", host: "localhost", referrer: "http://localhost/"
2020/11/05 12:05:55 [error] 32#32: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.16.1, server: , request: "GET / HTTP/1.1", upstream: "fastcgi://192.168.16.3:9000", host: "localhost"
2020/11/05 12:05:55 [error] 32#32: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.16.1, server: , request: "GET /favicon.ico HTTP/1.1", upstream: "fastcgi://192.168.16.3:9000", host: "localhost", referrer: "http://localhost/"
2020/11/05 12:05:57 [error] 32#32: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.16.1, server: , request: "GET / HTTP/1.1", upstream: "fastcgi://192.168.16.3:9000", host: "localhost"
2020/11/05 12:05:57 [error] 32#32: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.16.1, server: , request: "GET /favicon.ico HTTP/1.1", upstream: "fastcgi://192.168.16.3:9000", host: "localhost", referrer: "http://localhost/"
2020/11/05 12:05:57 [error] 32#32: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.16.1, server: , request: "GET / HTTP/1.1", upstream: "fastcgi://192.168.16.3:9000", host: "localhost"
2020/11/05 12:05:57 [error] 32#32: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.16.1, server: , request: "GET /favicon.ico HTTP/1.1", upstream: "fastcgi://192.168.16.3:9000", host: "localhost", referrer: "http://localhost/"
2020/11/05 12:05:58 [error] 32#32: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.16.1, server: , request: "GET / HTTP/1.1", upstream: "fastcgi://192.168.16.3:9000", host: "localhost"
2020/11/05 12:05:58 [error] 32#32: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.16.1, server: , request: "GET /favicon.ico HTTP/1.1", upstream: "fastcgi://192.168.16.3:9000", host: "localhost", referrer: "http://localhost/"
2020/11/05 12:05:58 [error] 32#32: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.16.1, server: , request: "GET / HTTP/1.1", upstream: "fastcgi://192.168.16.3:9000", host: "localhost"
2020/11/05 12:05:58 [error] 32#32: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.16.1, server: , request: "GET /favicon.ico HTTP/1.1", upstream: "fastcgi://192.168.16.3:9000", host: "localhost", referrer: "http://localhost/"
2020/11/05 12:05:59 [error] 32#32: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.16.1, server: , request: "GET / HTTP/1.1", upstream: "fastcgi://192.168.16.3:9000", host: "localhost"
2020/11/05 12:05:59 [error] 32#32: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.16.1, server: , request: "GET /favicon.ico HTTP/1.1", upstream: "fastcgi://192.168.16.3:9000", host: "localhost", referrer: "http://localhost/"
2020/11/05 12:05:59 [error] 32#32: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.16.1, server: , request: "GET / HTTP/1.1", upstream: "fastcgi://192.168.16.3:9000", host: "localhost"
2020/11/05 12:05:59 [error] 32#32: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.16.1, server: , request: "GET /favicon.ico HTTP/1.1", upstream: "fastcgi://192.168.16.3:9000", host: "localhost", referrer: "http://localhost/"
2020/11/05 12:06:00 [error] 32#32: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.16.1, server: , request: "GET / HTTP/1.1", upstream: "fastcgi://192.168.16.3:9000", host: "localhost"
2020/11/05 12:06:00 [error] 32#32: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.16.1, server: , request: "GET /favicon.ico HTTP/1.1", upstream: "fastcgi://192.168.16.3:9000", host: "localhost", referrer: "http://localhost/"
2020/11/05 12:06:00 [error] 32#32: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.16.1, server: , request: "GET / HTTP/1.1", upstream: "fastcgi://192.168.16.3:9000", host: "localhost"
2020/11/05 12:06:00 [error] 32#32: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.16.1, server: , request: "GET /favicon.ico HTTP/1.1", upstream: "fastcgi://192.168.16.3:9000", host: "localhost", referrer: "http://localhost/"
2020/11/05 12:06:01 [error] 32#32: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.16.1, server: , request: "GET / HTTP/1.1", upstream: "fastcgi://192.168.16.3:9000", host: "localhost"
2020/11/05 12:06:01 [error] 32#32: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.16.1, server: , request: "GET /favicon.ico HTTP/1.1", upstream: "fastcgi://192.168.16.3:9000", host: "localhost", referrer: "http://localhost/"
2020/11/05 12:06:01 [error] 32#32: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.16.1, server: , request: "GET / HTTP/1.1", upstream: "fastcgi://192.168.16.3:9000", host: "localhost"
2020/11/05 12:06:01 [error] 32#32: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.16.1, server: , request: "GET /favicon.ico HTTP/1.1", upstream: "fastcgi://192.168.16.3:9000", host: "localhost", referrer: "http://localhost/"
2020/11/05 12:06:02 [error] 32#32: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.16.1, server: , request: "GET / HTTP/1.1", upstream: "fastcgi://192.168.16.3:9000", host: "localhost"
2020/11/05 12:06:02 [error] 32#32: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.16.1, server: , request: "GET /favicon.ico HTTP/1.1", upstream: "fastcgi://192.168.16.3:9000", host: "localhost", referrer: "http://localhost/"
2020/11/05 12:06:03 [error] 32#32: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.16.1, server: , request: "GET / HTTP/1.1", upstream: "fastcgi://192.168.16.3:9000", host: "localhost"
2020/11/05 12:06:03 [error] 32#32: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.16.1, server: , request: "GET /favicon.ico HTTP/1.1", upstream: "fastcgi://192.168.16.3:9000", host: "localhost", referrer: "http://localhost/"
2020/11/05 12:06:03 [error] 32#32: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.16.1, server: , request: "GET / HTTP/1.1", upstream: "fastcgi://192.168.16.3:9000", host: "localhost"
2020/11/05 12:06:03 [error] 32#32: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.16.1, server: , request: "GET /favicon.ico HTTP/1.1", upstream: "fastcgi://192.168.16.3:9000", host: "localhost", referrer: "http://localhost/"
2020/11/05 12:06:04 [error] 32#32: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.16.1, server: , request: "GET / HTTP/1.1", upstream: "fastcgi://192.168.16.3:9000", host: "localhost"
2020/11/05 12:06:04 [error] 32#32: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.16.1, server: , request: "GET /favicon.ico HTTP/1.1", upstream: "fastcgi://192.168.16.3:9000", host: "localhost", referrer: "http://localhost/"
2020/11/05 12:06:04 [error] 32#32: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.16.1, server: , request: "GET / HTTP/1.1", upstream: "fastcgi://192.168.16.3:9000", host: "localhost"
2020/11/05 12:06:05 [error] 32#32: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.16.1, server: , request: "GET /favicon.ico HTTP/1.1", upstream: "fastcgi://192.168.16.3:9000", host: "localhost", referrer: "http://localhost/"
2020/11/05 12:06:05 [error] 32#32: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.16.1, server: , request: "GET / HTTP/1.1", upstream: "fastcgi://192.168.16.3:9000", host: "localhost"
2020/11/05 12:06:05 [error] 32#32: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.16.1, server: , request: "GET /favicon.ico HTTP/1.1", upstream: "fastcgi://192.168.16.3:9000", host: "localhost", referrer: "http://localhost/"
2020/11/05 12:06:06 [error] 32#32: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.16.1, server: , request: "GET / HTTP/1.1", upstream: "fastcgi://192.168.16.3:9000", host: "localhost"
2020/11/05 12:06:06 [error] 32#32: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.16.1, server: , request: "GET /favicon.ico HTTP/1.1", upstream: "fastcgi://192.168.16.3:9000", host: "localhost", referrer: "http://localhost/"
2020/11/05 12:06:06 [error] 32#32: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.16.1, server: , request: "GET / HTTP/1.1", upstream: "fastcgi://192.168.16.3:9000", host: "localhost"
2020/11/05 12:06:06 [error] 32#32: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.16.1, server: , request: "GET /favicon.ico HTTP/1.1", upstream: "fastcgi://192.168.16.3:9000", host: "localhost", referrer: "http://localhost/"
2020/11/05 12:06:06 [error] 32#32: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.16.1, server: , request: "GET / HTTP/1.1", upstream: "fastcgi://192.168.16.3:9000", host: "localhost"
2020/11/05 12:06:07 [error] 32#32: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.16.1, server: , request: "GET /favicon.ico HTTP/1.1", upstream: "fastcgi://192.168.16.3:9000", host: "localhost", referrer: "http://localhost/"
2020/11/05 12:06:07 [error] 32#32: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.16.1, server: , request: "GET / HTTP/1.1", upstream: "fastcgi://192.168.16.3:9000", host: "localhost"
2020/11/05 12:06:07 [error] 32#32: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.16.1, server: , request: "GET /favicon.ico HTTP/1.1", upstream: "fastcgi://192.168.16.3:9000", host: "localhost", referrer: "http://localhost/"
2020/11/05 12:06:07 [error] 32#32: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.16.1, server: , request: "GET / HTTP/1.1", upstream: "fastcgi://192.168.16.3:9000", host: "localhost"
2020/11/05 12:06:07 [error] 32#32: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.16.1, server: , request: "GET /favicon.ico HTTP/1.1", upstream: "fastcgi://192.168.16.3:9000", host: "localhost", referrer: "http://localhost/"
2020/11/05 12:06:07 [error] 32#32: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.16.1, server: , request: "GET / HTTP/1.1", upstream: "fastcgi://192.168.16.3:9000", host: "localhost"
2020/11/05 12:06:07 [error] 32#32: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.16.1, server: , request: "GET /favicon.ico HTTP/1.1", upstream: "fastcgi://192.168.16.3:9000", host: "localhost", referrer: "http://localhost/"
2020/11/05 12:06:08 [error] 32#32: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.16.1, server: , request: "GET / HTTP/1.1", upstream: "fastcgi://192.168.16.3:9000", host: "localhost"
2020/11/05 12:06:08 [error] 32#32: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.16.1, server: , request: "GET /favicon.ico HTTP/1.1", upstream: "fastcgi://192.168.16.3:9000", host: "localhost", referrer: "http://localhost/"
2020/11/05 12:06:08 [error] 32#32: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.16.1, server: , request: "GET / HTTP/1.1", upstream: "fastcgi://192.168.16.3:9000", host: "localhost"
2020/11/05 12:06:08 [error] 32#32: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.16.1, server: , request: "GET /favicon.ico HTTP/1.1", upstream: "fastcgi://192.168.16.3:9000", host: "localhost", referrer: "http://localhost/"
2020/11/05 12:06:08 [error] 32#32: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.16.1, server: , request: "GET / HTTP/1.1", upstream: "fastcgi://192.168.16.3:9000", host: "localhost"
2020/11/05 12:06:08 [error] 32#32: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.16.1, server: , request: "GET /favicon.ico HTTP/1.1", upstream: "fastcgi://192.168.16.3:9000", host: "localhost", referrer: "http://localhost/"
2020/11/05 12:54:29 [emerg] 1#1: host not found in upstream "php-fpm" in /etc/nginx/sites-available/default.conf:14
2020/11/05 13:00:07 [emerg] 1#1: host not found in upstream "php-fpm" in /etc/nginx/sites-available/default.conf:14
2020/11/05 13:33:19 [emerg] 1#1: host not found in upstream "php-fpm" in /etc/nginx/sites-available/default.conf:14
2020/11/22 20:54:44 [emerg] 1#1: host not found in upstream "php-fpm.default.svc.cluster.local" in /etc/nginx/sites-available/default.conf:14
